-- Kelime havuzu genişletildi: her seviyede en az 300 kelime (B1, B1+, B2, B2+).
-- Türkçe karşılık (tr) artık kullanılmıyor, yeni kelimelerde boş (NULL). Var olan kelimeler atlanır.

insert into public.words(lvl, word, def, tr, ex)
select v.l, v.w, v.d, null, v.e from (values
(0,'anchor','a heavy metal object that keeps a ship in one place','The sailors dropped the anchor near the island.'),
(0,'ankle','the joint between your foot and your leg','She hurt her ankle while playing football.'),
(0,'apron','clothing you wear over your clothes to keep them clean while cooking','My mother put on an apron before cooking.'),
(0,'arrow','a thin stick with a sharp point that is shot from a bow','The arrow hit the target in the middle.'),
(0,'attic','a room under the roof of a house','We keep old boxes in the attic.'),
(0,'barrel','a round wooden container for liquids','The barrel was full of water.'),
(0,'battle','a fight between two armies','Many soldiers died in the battle.'),
(0,'blade','the flat sharp part of a knife or sword','He cut the rope with the blade.'),
(0,'blossom','the flowers on a tree before the fruit grows','The cherry tree is covered in blossom.'),
(0,'boiling','so hot that bubbles rise in the water','Be careful, the water is boiling.'),
(0,'bonus','an extra amount of money or something good that you did not expect','All workers got a bonus at the end of the year.'),
(0,'brave','ready to face danger without showing fear','The brave boy saved his little sister.'),
(0,'breeze','a light and gentle wind','A cool breeze came through the window.'),
(0,'broom','a brush with a long handle for cleaning the floor','He swept the kitchen with a broom.'),
(0,'bruise','a dark mark on the skin after you hit something','She had a big bruise on her knee.'),
(0,'bulb','the glass part of a lamp that gives light','The bulb in the kitchen stopped working.'),
(0,'bump','a raised part on a surface or a small hit','I got a bump on my head when I fell.'),
(0,'bunch','a group of things of the same kind that are held or tied together','He bought a bunch of flowers for his mother.'),
(0,'cabin','a small wooden house in the forest or mountains','We stayed in a cabin by the lake.'),
(0,'calendar','a chart that shows the days and months of the year','I marked the exam date on the calendar.'),
(0,'campfire','a fire made outside where people camp','We sang songs around the campfire.'),
(0,'canal','a long narrow river made by people for boats','The boat moved slowly along the canal.'),
(0,'canoe','a light narrow boat moved with a paddle','They crossed the river in a canoe.'),
(0,'carriage','an old vehicle with wheels pulled by horses','The queen arrived in a golden carriage.'),
(0,'cashier','a person who takes your money in a shop','The cashier gave me my change.'),
(0,'cattle','cows and bulls kept on a farm','The farmer keeps cattle in the field.'),
(0,'cave','a large natural hole in the side of a hill or under the ground','Bats live in the dark cave.'),
(0,'ceiling','the top surface inside a room','A fly was walking on the ceiling.'),
(0,'century','a period of one hundred years','The castle was built in the fifteenth century.'),
(0,'cereal','a breakfast food made from grain and eaten with milk','I eat a bowl of cereal every morning.'),
(0,'chapter','one of the main parts of a book','I read the first chapter last night.'),
(0,'chart','a drawing that shows information in a simple way','The chart shows how the temperature changes.'),
(0,'cheerful','happy and full of energy','The cheerful boy smiled at everyone.'),
(0,'chest','the front part of your body between your neck and your stomach','He felt pain in his chest.'),
(0,'chimney','a tall pipe above a fire that lets smoke out','Smoke was coming out of the chimney.'),
(0,'chopsticks','two thin sticks used for eating in East Asia','She picked up the rice with chopsticks.'),
(0,'clue','a piece of information that helps you solve a problem','The police found a clue near the door.'),
(0,'coach','a person who trains a sports team','The coach asked us to run ten laps.'),
(0,'comb','a flat tool with teeth that you use to tidy your hair','He used a comb to fix his hair.'),
(0,'compass','a tool with a needle that shows you which direction is north','The hikers used a compass to find the way.'),
(0,'concert','a public performance of music','We went to a rock concert last night.'),
(0,'cottage','a small house in the countryside','They spent the weekend in a cottage.'),
(0,'cradle','a small bed for a baby that can move from side to side','She rocked the baby in the cradle.'),
(0,'crater','a large round hole in the ground or at the top of a volcano','The astronauts walked near a deep crater.'),
(0,'crew','all the people who work on a ship, plane or film','The crew welcomed the passengers on board.'),
(0,'crispy','hard and thin in a pleasant way when you bite it','The chicken was hot and crispy.'),
(0,'crumb','a very small piece of bread or cake','There were crumb marks all over the table.'),
(0,'cushion','a soft bag that you put on a chair or sofa','She put a cushion behind her back.'),
(0,'dairy','made from milk, like cheese and butter','He cannot eat dairy products.'),
(0,'dawn','the time of day when light first appears in the morning','The farmers get up at dawn.'),
(0,'deck','the flat surface on a ship that you can walk on','We stood on the deck and watched the sea.'),
(0,'detective','a person whose job is to find out who committed a crime','The detective questioned the witness.'),
(0,'dock','a place where ships stop to load and unload','The ship waited at the dock.'),
(0,'dough','a thick mixture of flour and water used for making bread','She made dough for the pizza.'),
(0,'drain','a pipe that carries away dirty water','The water ran down the drain.'),
(0,'dusty','covered with dry powder from the ground or air','The old books were dusty.'),
(0,'dragon','an imaginary animal that breathes fire','The knight fought a dragon in the story.'),
(0,'eyebrow','the line of short hair above your eye','He raised his eyebrow in surprise.'),
(0,'eyelash','one of the short hairs on the edge of your eyelid','A tiny eyelash fell onto her cheek.'),
(0,'factory','a building where goods are made by machines','The factory makes toys.'),
(0,'fairy','a small imaginary creature with magic powers','The fairy gave her three wishes.'),
(0,'feast','a large and special meal','They prepared a big feast for the wedding.'),
(0,'ferry','a boat that carries people across water','We took the ferry to the island.'),
(0,'festival','a special event with music and celebrations','The town holds a music festival every summer.'),
(0,'firework','an object that makes bright lights and noise in the sky','The children loved the firework display.'),
(0,'fireplace','a space in a wall where you can light a fire','We sat near the fireplace and talked.'),
(0,'flame','the hot bright part of a fire','The flame went out in the wind.'),
(0,'flashlight','a small electric light that you carry in your hand','He used a flashlight to look under the bed.'),
(0,'flavour','the taste of a food or drink','My favourite ice cream flavour is vanilla.'),
(0,'flood','a large amount of water covering land that is usually dry','The flood destroyed many houses.'),
(0,'foggy','full of thick cloud near the ground that makes it hard to see','It was a foggy morning and the roads were dangerous.'),
(0,'footprint','a mark made by a foot','We saw a footprint in the wet sand.'),
(0,'fossil','the old remains of an animal or plant found in rock','The scientist found a fossil of a fish.'),
(0,'frame','a border around a picture or door','She put the photo in a wooden frame.'),
(0,'freckle','a small brown spot on the skin','He has a freckle on his nose.'),
(0,'freezer','a machine that keeps food frozen','Put the ice cream back in the freezer.'),
(0,'gallery','a building where people look at paintings','We spent the afternoon in an art gallery.'),
(0,'garlic','a strong-smelling vegetable used in cooking','Add some garlic to the sauce.'),
(0,'glacier','a huge mass of ice that moves very slowly','The glacier is melting every year.'),
(0,'goggles','special glasses that protect your eyes','She wore goggles in the swimming pool.'),
(0,'gravity','the force that pulls things towards the earth','Gravity makes the apple fall from the tree.'),
(0,'grill','a metal frame used to cook food over a fire','Dad cooked the meat on the grill.'),
(0,'hallway','a passage inside a building with doors on each side','Please leave your shoes in the hallway.'),
(0,'handle','the part of something that you hold in your hand','The handle of the cup broke.'),
(0,'headache','a pain in your head','I took a pill because I had a headache.'),
(0,'hedgehog','a small animal with sharp spines on its back','A hedgehog was hiding under the bush.'),
(0,'hiccup','a sudden noise in your throat that you cannot control','I got a hiccup after drinking too fast.'),
(0,'hollow','having an empty space inside','The squirrel lives in a hollow tree.'),
(0,'horizon','the line where the sky seems to meet the land or sea','The sun disappeared below the horizon.'),
(0,'hunger','the feeling you have when you need food','Hunger made it hard to study.'),
(0,'igloo','a house made from blocks of snow','The explorers built an igloo for the night.'),
(0,'jelly','a soft sweet food made from fruit juice that shakes when you touch it','The children ate jelly and ice cream.'),
(0,'jungle','a thick tropical forest','Monkeys live in the jungle.'),
(0,'kettle','a container used for boiling water','She filled the kettle and made tea.'),
(0,'kitten','a very young cat','The kitten drank milk from a small bowl.'),
(0,'knot','a place where string or rope is tied together','He tied a knot in the rope.'),
(0,'lantern','a light in a glass case that you can carry','The villagers lit a lantern in the dark.'),
(0,'lawn','an area of short grass around a house','He cuts the lawn every Saturday.'),
(0,'layer','a flat amount of something that covers a surface or lies between others','There was a thin layer of snow on the road.'),
(0,'leather','a strong material made from animal skin','His shoes are made of leather.'),
(0,'lifeguard','a person who watches swimmers and saves them from danger','The lifeguard jumped into the water.'),
(0,'lighthouse','a tall building with a bright light that guides ships','The lighthouse showed the ships the way.'),
(0,'lizard','a small reptile with a long tail','A lizard ran across the warm rock.'),
(0,'lobster','a sea animal with a hard shell and big claws','They ate lobster at the restaurant.'),
(0,'magnet','an object that pulls iron towards it','The magnet picked up all the pins.'),
(0,'marble','a small glass ball used in children''s games','He lost his favourite marble under the sofa.'),
(0,'mask','a cover that you wear over your face','She wore a mask to the party.'),
(0,'mattress','the soft part of a bed that you lie on','This mattress is very comfortable.'),
(0,'mayor','the person who is the head of a town or city','The mayor opened the new library.'),
(0,'meadow','a field of grass and wild flowers','Cows were eating in the meadow.'),
(0,'microscope','a tool that makes very small things look bigger','We looked at a leaf under the microscope.'),
(0,'mill','a building where grain is made into flour','The old mill stands next to the river.'),
(0,'miner','a person who works under the ground to get coal or gold','The miner wore a lamp on his helmet.'),
(0,'mist','a thin cloud of water drops near the ground','A light mist covered the hills.'),
(0,'mitten','a glove with one part for the thumb and one for the fingers','She lost one mitten in the snow.'),
(0,'mosquito','a small flying insect that bites people','A mosquito bit me last night.'),
(0,'muscle','a part of the body that helps you move','He trains every day to build muscle.'),
(0,'napkin','a piece of cloth or paper used to clean your mouth at meals','Please put the napkin on your lap.'),
(0,'needle','a thin sharp tool used for sewing','She sewed the button with a needle and thread.'),
(0,'neighbour','a person who lives near you','Our neighbour often helps us with the garden.'),
(0,'nephew','the son of your brother or sister','My nephew is learning to swim.'),
(0,'nest','a home that a bird makes for its eggs','The bird built a nest in the tree.'),
(0,'niece','the daughter of your brother or sister','I bought a toy for my niece.'),
(0,'nickname','a friendly name used instead of your real name','His nickname at school is Tiny.'),
(0,'novel','a long written story about imaginary people','She is reading a novel about a pirate.'),
(0,'orchard','a field where fruit trees grow','We picked apples in the orchard.'),
(0,'ostrich','a very large bird that cannot fly but runs fast','The ostrich ran across the field.'),
(0,'paddle','a short pole with a flat end used to move a small boat','He used a paddle to cross the river.'),
(0,'palace','a very large house where a king or queen lives','The tourists visited the old palace.'),
(0,'parade','a public march with music and people in costumes','The children watched the parade on the street.'),
(0,'parcel','something wrapped in paper to send by post','I got a parcel from my aunt.'),
(0,'pasta','a food made from flour and water in different shapes','We had pasta with tomato sauce.'),
(0,'pavement','the path at the side of a road for people who walk','Do not ride your bike on the pavement.'),
(0,'pedal','the part of a bike that you push with your foot','He pushed hard on the pedal.'),
(0,'perfume','a liquid with a pleasant smell that you put on your skin','She wore a light perfume.'),
(0,'pickle','a vegetable kept in vinegar or salt water','He put a pickle in his sandwich.'),
(0,'picnic','a meal eaten outside in a park or field','We had a picnic by the river.'),
(0,'pigeon','a grey bird that often lives in cities','A pigeon sat on the roof.'),
(0,'pirate','a person who attacks ships to steal from them','The pirate hid the gold on the island.'),
(0,'plaster','a small cover you put on a cut','I put a plaster on my finger.'),
(0,'plumber','a person who fixes water pipes','The plumber fixed the leaking tap.'),
(0,'pond','a small area of water in a garden or field','Ducks swam on the pond.'),
(0,'porch','a covered area at the entrance of a house','We sat on the porch and drank lemonade.'),
(0,'postcard','a card with a picture that you send without an envelope','She sent me a postcard from Rome.'),
(0,'pottery','objects made from baked clay','She took a pottery class on Saturdays.'),
(0,'pump','a machine that moves liquid or air','He used a pump to fill the tyre.'),
(0,'raft','a flat boat made from pieces of wood tied together','They floated down the river on a raft.'),
(0,'ranch','a very large farm where cows or horses are kept','They keep horses on their ranch.'),
(0,'razor','a sharp tool used to remove hair from the skin','He cut himself with the razor.'),
(0,'reef','a line of rocks or coral near the surface of the sea','Colourful fish live on the reef.'),
(0,'ribbon','a long thin piece of cloth used for tying or decorating','She tied a red ribbon around the gift.'),
(0,'rocket','a vehicle that travels into space','The rocket flew to the moon.'),
(0,'rope','a thick strong cord made of twisted threads','He climbed up the rope.'),
(0,'rust','the red-brown layer that forms on iron when it gets wet','There was rust on the old bicycle.'),
(0,'sack','a large strong bag','He carried a sack of potatoes.'),
(0,'saddle','a seat that you sit on when riding a horse','He put the saddle on the horse.'),
(0,'sail','a large piece of cloth that catches the wind and moves a boat','The wind filled the sail.'),
(0,'sandal','a light shoe with straps that is worn in warm weather','Her left sandal came off in the water.'),
(0,'satellite','an object sent into space to travel around the earth','The satellite sends pictures of the weather.'),
(0,'scar','a mark left on the skin after a wound has healed','He has a scar on his arm from the accident.'),
(0,'scenery','the natural beauty of a place','We enjoyed the mountain scenery from the train.'),
(0,'shadow','a dark shape made when something blocks the light','The tree made a long shadow on the grass.'),
(0,'shark','a large fish with sharp teeth','A shark swam near the boat.'),
(0,'shell','the hard outside part of an egg, a nut or a sea animal','She picked up a shell on the beach.'),
(0,'shelf','a flat board on a wall for putting things on','Put the book back on the shelf.'),
(0,'shiver','to shake because you are cold or scared','I began to shiver in the cold wind.'),
(0,'shore','the land at the edge of the sea or a lake','We walked along the shore at sunset.'),
(0,'shovel','a tool with a long handle for digging','He used a shovel to dig a hole in the garden.'),
(0,'skeleton','all the bones in a body','The museum has a dinosaur skeleton.'),
(0,'sketch','a quick simple drawing','He made a sketch of the old bridge.'),
(0,'sleeve','the part of a coat or shirt that covers your arm','He rolled up his sleeve.'),
(0,'slope','a surface that goes up or down at an angle','The children ran down the grassy slope.'),
(0,'smoke','the grey cloud that rises from a fire','Smoke came out of the chimney.'),
(0,'snail','a small slow animal with a shell on its back','A snail was moving across the leaf.'),
(0,'sneeze','to blow air out of your nose suddenly','The dust made me sneeze.'),
(0,'soil','the earth in which plants grow','The soil in this garden is very rich.'),
(0,'souvenir','something you buy to remember a place you visited','I bought a small souvenir at the airport.'),
(0,'spice','a strong-tasting powder or seed that is used to add flavour to food','Add a little spice to the soup.'),
(0,'squirrel','a small animal with a bushy tail that lives in trees','A squirrel ran up the tree with a nut.'),
(0,'statue','a figure of a person or animal made of stone or metal','There is a statue of the king in the square.'),
(0,'steam','the hot white cloud that rises from boiling water','Steam rose from the cup.'),
(0,'stitch','a small loop of thread made with a needle','The doctor closed the cut with one stitch.'),
(0,'stomach','the part of the body where food goes after you swallow','My stomach hurts after lunch.'),
(0,'storm','very bad weather with strong wind and rain','The storm knocked down several trees.'),
(0,'strap','a narrow piece of leather or cloth used to hold something','The strap of my bag broke.'),
(0,'stream','a small narrow river','They crossed the stream on stones.'),
(0,'string','a thin cord used for tying things','He tied the box with string.'),
(0,'sunflower','a tall yellow flower with a large round centre','The sunflower turned to face the sun.'),
(0,'swamp','an area of wet soft land','Crocodiles live in the swamp.'),
(0,'swing','a seat that hangs from ropes and moves back and forth','The little girl played on the swing.'),
(0,'tablet','a flat computer you use with your fingers','He reads books on his tablet.'),
(0,'tadpole','a young frog that lives in water','The tadpole will slowly grow into a frog.'),
(0,'teapot','a container with a spout for making tea','She poured tea from the teapot.'),
(0,'thread','a long thin piece of cotton or silk used for sewing','She needed a needle and thread.'),
(0,'tide','the regular rise and fall of the sea','The tide came in and covered the rocks.'),
(0,'toolbox','a box where you keep your tools','Dad opened the toolbox and took out a hammer.'),
(0,'torch','a small electric light that you hold in your hand','He used a torch to find his way in the dark.'),
(0,'tournament','a competition in which many players or teams take part','Our school won the chess tournament.'),
(0,'tower','a tall narrow building or part of a building','We climbed to the top of the tower.'),
(0,'trail','a path through the countryside or forest','We followed the trail up the hill.'),
(0,'tray','a flat object for carrying food and drinks','The waiter carried the tray carefully.'),
(0,'trophy','a prize such as a metal cup that you win','The team lifted the trophy.'),
(0,'trumpet','a brass instrument you blow into','He plays the trumpet in the school band.'),
(0,'tunnel','a long passage under the ground or through a mountain','The train went through a tunnel.'),
(0,'twig','a small thin branch of a tree','The bird carried a twig to its nest.'),
(0,'uniform','special clothes worn by people in the same school or job','Students wear a uniform at our school.'),
(0,'vase','a container for putting cut flowers in','She put the roses in a vase.'),
(0,'vest','a piece of clothing worn on the upper body without sleeves','He wore a vest under his shirt.'),
(0,'violin','a musical instrument with strings that you play with a bow','She practises the violin every evening.'),
(0,'walnut','a hard nut with a wrinkled shape','She added walnut pieces to the cake.'),
(0,'waterfall','water that falls from a high place in a river','We took photos next to the waterfall.'),
(0,'whistle','a small tool that makes a high sound when you blow it','The referee blew his whistle.'),
(0,'wizard','a man in stories who has magic powers','The wizard turned the frog into a prince.'),
(0,'worm','a long thin soft animal that lives in the soil','The bird pulled a worm out of the ground.'),
(0,'wrist','the joint between your hand and your arm','He wears a watch on his wrist.')
) as v(l, w, d, e)
where not exists (select 1 from public.words x where x.word = v.w);

insert into public.words(lvl, word, def, tr, ex)
select v.l, v.w, v.d, null, v.e from (values
(1,'abandon','to leave something or someone and never come back','The sailors had to abandon the sinking ship.'),
(1,'abroad','in or to a foreign country','She wants to study abroad next year.'),
(1,'absent','not present at a place where you should be','He was absent from school on Monday.'),
(1,'access','the right or way to use or enter something','Students have access to the library all day.'),
(1,'achievement','something good that you have done with effort','Finishing the marathon was a great achievement.'),
(1,'adopt','to take a child or animal into your family','They decided to adopt a puppy from the shelter.'),
(1,'advertise','to tell people about a product so they will buy it','The company will advertise the new phone on TV.'),
(1,'afford','to have enough money to pay for something','We cannot afford a new car this year.'),
(1,'agency','a business that provides a particular service','She works for a travel agency.'),
(1,'alert','watching carefully and ready to act','The guard stayed alert all night.'),
(1,'alternative','another thing you can choose instead','Is there an alternative to this road?'),
(1,'amateur','a person who does something for pleasure and not as a job','He is an amateur photographer.'),
(1,'amaze','to surprise someone very much','Her speed will amaze you.'),
(1,'ancestor','a family member who lived a long time ago','My ancestor came from the mountains.'),
(1,'announce','to tell people something officially','The teacher will announce the results tomorrow.'),
(1,'annoy','to make someone slightly angry','Loud music can annoy the neighbours.'),
(1,'apparent','easy to see or understand','It was apparent that she was very tired.'),
(1,'appeal','a quality that makes people like something','The film has a wide appeal for young people.'),
(1,'appetite','the feeling that you want to eat food','The long walk gave us a good appetite.'),
(1,'aware','knowing that something exists or is happening','Are you aware of the problem?'),
(1,'barrier','something that blocks the way or stops progress','Language can be a barrier when you travel.'),
(1,'boost','to make something increase or improve','A good night''s sleep will boost your energy.'),
(1,'brilliant','very clever or very bright','She had a brilliant idea for the project.'),
(1,'broadcast','to send out a programme on radio or television','The match will be broadcast live tonight.'),
(1,'bully','a person who uses strength to frighten weaker people','The teacher stopped the bully in the playground.'),
(1,'burden','something difficult or heavy that you have to carry or deal with','The loan was a heavy burden for the family.'),
(1,'campaign','a planned series of actions to achieve a goal','They started a campaign to save the old park.'),
(1,'candidate','a person who is trying to get a job or win an election','Each candidate gave a short speech.'),
(1,'cargo','goods carried by a ship, plane or truck','The ship carried a cargo of oranges.'),
(1,'casual','relaxed and not formal','He wore casual clothes to the party.'),
(1,'cautious','careful to avoid danger or mistakes','Be cautious when you cross the busy road.'),
(1,'ceremony','a formal event held on an important occasion','The graduation ceremony starts at ten.'),
(1,'charity','an organisation that helps people in need','She gave her old clothes to charity.'),
(1,'chase','to run after someone in order to catch them','The dog began to chase the cat.'),
(1,'citizen','a person who legally belongs to a country','Every citizen has the right to vote.'),
(1,'collapse','to fall down suddenly','The old bridge could collapse in the storm.'),
(1,'commute','to travel regularly between home and work','He commutes to the city by train.'),
(1,'competition','an event in which people try to win','She won first prize in the singing competition.'),
(1,'complain','to say that you are not happy about something','Customers complain about the slow service.'),
(1,'complaint','a statement that something is wrong','The shop received a complaint about the noise.'),
(1,'compliment','a kind thing you say to praise someone','He gave her a compliment about her dress.'),
(1,'concentrate','to give all your attention to one thing','I cannot concentrate with the TV on.'),
(1,'condition','the state that something or someone is in','The old car is still in good condition.'),
(1,'confirm','to say or show that something is true','Please confirm your booking by email.'),
(1,'consider','to think carefully about something','Consider all the options before you decide.'),
(1,'courage','the ability to do something that frightens you','It took a lot of courage to speak in front of everyone.'),
(1,'crisis','a time of great danger or difficulty','The country faced an economic crisis.'),
(1,'cruel','causing pain to others on purpose','It is cruel to hurt animals.'),
(1,'curiosity','the strong wish to know or learn something','Curiosity made her open the box.'),
(1,'currency','the money used in a particular country','The currency of Japan is the yen.'),
(1,'custom','a way of behaving that is usual in a group or country','It is the custom to take off your shoes here.'),
(1,'debt','money that you owe to someone','He worked hard to pay off his debt.'),
(1,'decade','a period of ten years','They have lived here for a decade.'),
(1,'defeat','to win against someone in a game or fight','Our team will defeat them on Saturday.'),
(1,'defend','to protect someone or something from attack','The soldiers defend the border.'),
(1,'delicate','easy to break or damage','Be careful with the delicate glass.'),
(1,'democracy','a system where people choose their leaders by voting','Many countries now live in a democracy.'),
(1,'departure','the act of leaving a place','The departure of the train was delayed.'),
(1,'depend','to be decided by something else','The picnic depends on the weather.'),
(1,'destiny','the events that will happen to you in the future','She believes it was her destiny to become a doctor.'),
(1,'detail','a small fact or piece of information','Tell me every detail of your trip.'),
(1,'device','a small machine made for a particular purpose','This device measures your heart rate.'),
(1,'disappear','to go away so that you cannot be seen','The magician made the coin disappear.'),
(1,'discourage','to make someone feel less confident about doing something','Failure should not discourage you.'),
(1,'domestic','connected with the home or with your own country','Cats and dogs are domestic animals.'),
(1,'drought','a long period with no rain','The drought destroyed the crops.'),
(1,'eager','wanting very much to do something','The children were eager to start the game.'),
(1,'edge','the outer part of something where it ends','He stood at the edge of the cliff.'),
(1,'election','an event in which people vote to choose a leader','The election will be held in May.'),
(1,'embarrass','to make someone feel shy or uncomfortable','Do not embarrass him in front of his friends.'),
(1,'encourage','to give someone hope and confidence','My parents always encourage me to try new things.'),
(1,'entertain','to amuse people in an enjoyable way','The magician will entertain the children.'),
(1,'environment','the natural world around us','We should protect the environment.'),
(1,'estimate','to guess an amount or value after thinking about it','I estimate that the trip will cost one hundred dollars.'),
(1,'evidence','facts that show that something is true','The police found new evidence at the scene.'),
(1,'examine','to look at something very carefully','The doctor will examine your knee.'),
(1,'exhausted','extremely tired','They were exhausted after climbing the mountain.'),
(1,'expedition','a long journey made for a special purpose','The expedition travelled to the North Pole.'),
(1,'explore','to travel around a place to learn about it','We want to explore the old city.'),
(1,'export','to sell goods to another country','Turkey will export more fruit this year.'),
(1,'extend','to make something longer or larger','They plan to extend the road to the village.'),
(1,'extreme','very great in degree','The desert has extreme heat in the summer.'),
(1,'fabric','cloth made by weaving threads together','The curtains are made of soft fabric.'),
(1,'fault','a mistake or something wrong that someone is responsible for','It was my fault that we were late.'),
(1,'feature','an important or interesting part of something','The camera has many useful features.'),
(1,'fiction','stories that are not about real people or events','She likes to read fiction at night.'),
(1,'flexible','able to change easily or bend without breaking','The job has flexible working hours.'),
(1,'forecast','a statement about what will happen in the future','The weather forecast says it will rain.'),
(1,'forgive','to stop being angry with someone for a mistake','I forgive you for forgetting my birthday.'),
(1,'fragile','easily broken or damaged','Be careful, the box contains fragile glasses.'),
(1,'frequent','happening often','He makes frequent visits to his grandmother.'),
(1,'fulfil','to do what is needed or promised','She worked hard to fulfil her dream.'),
(1,'generate','to produce energy or something else','Wind can generate electricity.'),
(1,'generous','willing to give money or time freely','He is generous and shares his food.'),
(1,'glance','to look at something quickly','She had a glance at the clock.'),
(1,'grateful','feeling thankful for something','I am grateful for your help.'),
(1,'guilty','feeling bad because you have done something wrong','He felt guilty about lying to his teacher.'),
(1,'habitat','the natural home of an animal or plant','The forest is the habitat of many birds.'),
(1,'harm','to hurt or damage someone or something','Smoking can harm your health.'),
(1,'heritage','traditions and buildings that come from the past','The old castle is part of our national heritage.'),
(1,'humble','not proud and not thinking you are better than others','Despite his fame, he remained humble.'),
(1,'hygiene','the practice of keeping yourself and things clean','Good hygiene prevents many diseases.'),
(1,'imagine','to form a picture of something in your mind','Imagine you are on a beach.'),
(1,'immigrant','a person who comes to live in a new country','Her parents are immigrants from Germany.'),
(1,'impact','a strong effect that something has on someone or something','The new law had a big impact on traffic.'),
(1,'import','to bring goods into a country to sell them','The country has to import oil.'),
(1,'influence','to change how someone thinks or behaves','Friends can influence your decisions.'),
(1,'inhabitant','a person who lives in a particular place','The town has about ten thousand inhabitants.'),
(1,'injure','to hurt a person or animal','He fell and injured his arm.'),
(1,'innocent','not guilty of a crime','The judge decided that he was innocent.'),
(1,'insult','to say something rude that hurts someone''s feelings','Do not insult your classmates.'),
(1,'intend','to plan to do something','I intend to learn French next year.'),
(1,'interrupt','to stop someone while they are speaking','Please do not interrupt me when I am talking.'),
(1,'invade','to enter a country with an army to take control','The army tried to invade the island.'),
(1,'invest','to put money into something to make more money','They decided to invest in a new business.'),
(1,'jealous','feeling unhappy because someone has something you want','She was jealous of her sister''s new bike.'),
(1,'journalist','a person who writes news for a newspaper or TV','The journalist interviewed the mayor.'),
(1,'landscape','everything you can see when you look across an area of land','The landscape was full of green hills.'),
(1,'launch','to start something new or send a rocket into the sky','They will launch the new product in June.'),
(1,'leisure','time when you are free to do what you want','He plays chess in his leisure time.'),
(1,'liberty','the freedom to live as you choose','The statue is a symbol of liberty.'),
(1,'locate','to find where something is','Can you locate the town on the map?'),
(1,'luxury','great comfort and expensive things','They stayed at a hotel with every luxury.'),
(1,'massive','extremely large and heavy','A massive rock blocked the road.'),
(1,'measure','to find the size or amount of something','Please measure the length of the table.'),
(1,'merchant','a person who buys and sells goods in large amounts','The merchant sold silk to Europe.'),
(1,'miserable','extremely unhappy','He felt miserable in the cold rain.'),
(1,'mission','an important job that someone is sent to do','The astronauts completed their mission.'),
(1,'mystery','something strange that no one can explain','The missing key remained a mystery.'),
(1,'narrow','small in width','The street was too narrow for cars.'),
(1,'nerve','a thin fibre that carries messages between the brain and the body','The dentist touched a nerve.'),
(1,'neglect','to fail to take care of something','He neglected his garden for years.'),
(1,'nonsense','words or ideas that have no sense','What he said was complete nonsense.'),
(1,'obey','to do what you are told to do','Dogs must obey their owners.'),
(1,'observe','to watch something carefully','Scientists observe the stars at night.'),
(1,'obtain','to get something, often with effort','You can obtain a ticket at the station.'),
(1,'offend','to hurt someone''s feelings','I did not mean to offend you.'),
(1,'ordinary','not special or different in any way','It was an ordinary day at school.'),
(1,'organise','to arrange or plan an event carefully','Students organise a book sale every year.'),
(1,'pace','the speed at which something moves','He walked at a slow pace.'),
(1,'panic','a sudden strong feeling of fear','The loud noise caused panic in the crowd.'),
(1,'partner','a person you do an activity or business with','Choose a partner for the dance.'),
(1,'passion','a very strong feeling of love or interest','Music is her passion.'),
(1,'patience','the ability to wait calmly without getting angry','Teaching children needs a lot of patience.'),
(1,'peaceful','calm and quiet','The village is a peaceful place.'),
(1,'perform','to do something in front of an audience','The band will perform at the festival.'),
(1,'permit','to allow someone to do something','Smoking is not permitted in the building.'),
(1,'persuade','to make someone agree to do something','She managed to persuade him to join the team.'),
(1,'pioneer','a person who is the first to do or discover something','He was a pioneer of modern medicine.'),
(1,'plenty','a large amount that is more than enough','We have plenty of time before the train.'),
(1,'policy','a plan of action agreed by a group or government','The school has a strict policy on phones.'),
(1,'portion','an amount of food for one person','He ordered a large portion of fries.'),
(1,'poverty','the state of being very poor','Many families live in poverty.'),
(1,'predict','to say what will happen in the future','No one can predict the weather exactly.'),
(1,'pretend','to behave as if something is true when it is not','The children pretend to be pirates.'),
(1,'privacy','the right to be alone and keep personal things secret','Everyone needs some privacy.'),
(1,'profit','money that you gain when you sell something for more than it cost','The shop made a profit this year.'),
(1,'progress','improvement or movement towards a goal','You are making good progress in English.'),
(1,'protest','a strong complaint shown in public','People held a protest against the new road.'),
(1,'publish','to print a book or article for people to buy or read','The company will publish her first novel.'),
(1,'punish','to make someone suffer for doing something wrong','Teachers should not punish students unfairly.'),
(1,'quality','how good or bad something is','This shop sells goods of high quality.'),
(1,'quarrel','an angry argument','The brothers had a quarrel about the game.'),
(1,'rapid','happening very quickly','The city''s growth was rapid.'),
(1,'rare','not found or seen very often','A rare bird landed in our garden.'),
(1,'reality','the way things really are','His dream finally became a reality.'),
(1,'recall','to remember something from the past','I cannot recall his name.'),
(1,'reduce','to make something smaller or less','We must reduce the amount of plastic we use.'),
(1,'reflect','to send back light or an image','The lake reflects the mountains.'),
(1,'refugee','a person who has to leave their country to be safe','The refugee found a new home in a small town.'),
(1,'reject','to refuse to accept something or someone','The company rejected his offer.'),
(1,'release','to let someone or something go free','They will release the birds into the forest.'),
(1,'remote','far away from other places','They live in a remote village in the mountains.'),
(1,'rescue','to save someone from danger','The firefighters rescue the cat from the tree.'),
(1,'resist','to fight against something or not give in','I cannot resist chocolate cake.'),
(1,'respond','to say or do something as an answer','Please respond to my email quickly.'),
(1,'retire','to stop working because of age','My grandfather retired last year.'),
(1,'revenge','harm done to someone because they harmed you','He wanted revenge for the unfair loss.'),
(1,'reward','something given for good work or behaviour','The police offered a reward for the lost dog.'),
(1,'rhythm','a regular pattern of sounds in music','The drummer kept a steady rhythm.'),
(1,'risk','the possibility that something bad may happen','Driving fast is a big risk.'),
(1,'rival','a person or team that competes with another','The two rival teams met in the final.'),
(1,'rough','not smooth or gentle','The sea was rough during the storm.'),
(1,'routine','the usual way of doing things','My morning routine starts with a cold shower.'),
(1,'rumour','a story that people repeat but may not be true','There is a rumour that the school will close.'),
(1,'scandal','an event that shocks people because of bad behaviour','The scandal ended the mayor''s career.'),
(1,'scholarship','money given to a student to pay for their studies','She won a scholarship to study in London.'),
(1,'secure','safe and protected from danger','Make sure the door is secure before you leave.'),
(1,'selfish','caring only about yourself','Do not be selfish and share your toys.'),
(1,'sensible','having good judgement and practical','It is sensible to carry an umbrella in autumn.'),
(1,'series','a number of things that follow one after another','He watches a new series every week.'),
(1,'settle','to make a permanent home in a place','They decided to settle in a small town.'),
(1,'severe','very bad or serious','A severe storm hit the coast.'),
(1,'shame','a painful feeling after doing something wrong','He felt shame about cheating on the exam.'),
(1,'signature','your name written by yourself','Please put your signature at the bottom.'),
(1,'skill','the ability to do something well','Cooking is a useful skill.'),
(1,'slight','small in size or degree','There was a slight change in the weather.'),
(1,'solution','an answer to a problem','We found a solution to the traffic problem.'),
(1,'source','the place where something comes from','The river''s source is in the mountains.'),
(1,'species','a group of animals or plants of the same kind','Many species of birds live in the forest.'),
(1,'spirit','the part of a person that is not the body','The team showed great spirit.'),
(1,'stable','firm and not likely to change or fall','The ladder is stable on flat ground.'),
(1,'steady','continuing in a regular way without sudden changes','He walked at a steady pace.'),
(1,'stranger','a person you do not know','Never talk to a stranger online.'),
(1,'stress','worry caused by problems in your life','Exams cause a lot of stress.'),
(1,'strict','demanding that rules are followed','Our teacher is strict but fair.'),
(1,'suffer','to feel pain or sadness','Many people suffer from headaches.'),
(1,'suggest','to offer an idea for someone to consider','I suggest we meet at six.'),
(1,'suitable','right for a particular person or purpose','This film is not suitable for children.'),
(1,'supply','to give or sell something that is needed','The farm will supply fresh milk to the school.'),
(1,'support','to help someone by encouraging them','My family always support me.'),
(1,'suspect','to think that someone has done something wrong','The police suspect that he took the money.'),
(1,'talent','a natural ability to do something well','He has a great talent for music.'),
(1,'target','something you aim at or try to achieve','He hit the target with his first arrow.'),
(1,'tempt','to make someone want to do something that is not wise','The smell of fresh bread can tempt anyone.'),
(1,'terrify','to make someone extremely afraid','Thunder can terrify small children.'),
(1,'theory','an idea that explains how something works','Einstein had a famous theory about time.'),
(1,'threaten','to say that you will hurt someone','The storm threatens to flood the town.'),
(1,'thrill','a sudden strong feeling of excitement','Riding the roller coaster gave her a thrill.'),
(1,'tolerate','to accept something unpleasant without complaining','I cannot tolerate loud noises.'),
(1,'tough','strong or difficult','It was a tough exam.'),
(1,'trace','a mark or sign left by someone or something','There was no trace of the thief.'),
(1,'trade','the buying and selling of goods','Trade between the two countries is growing.'),
(1,'tragedy','a very sad event','The flood was a terrible tragedy for the village.'),
(1,'transport','a system for moving people and goods','Public transport in the city is cheap.'),
(1,'trap','a device for catching animals or people','The mouse was caught in the trap.'),
(1,'treasure','a collection of valuable things like gold and jewels','The pirates buried their treasure on the island.'),
(1,'trust','to believe that someone is honest or reliable','You can trust me with your secret.'),
(1,'unique','being the only one of its kind','Every snowflake is unique.'),
(1,'urgent','needing immediate action','I have an urgent message for you.'),
(1,'vacant','not being used or lived in','There is a vacant seat at the back.'),
(1,'valuable','worth a lot of money or very useful','This old coin is very valuable.'),
(1,'variety','a number of different kinds of the same thing','The shop sells a wide variety of cheeses.'),
(1,'victim','a person who is hurt or killed by a crime or accident','The victim of the robbery called the police.'),
(1,'violence','behaviour that is intended to hurt people','The film contains scenes of violence.'),
(1,'vital','extremely important and necessary','Water is vital for all living things.'),
(1,'wander','to walk without a clear direction','We like to wander through the old streets.'),
(1,'warn','to tell someone about a possible danger','The sign warns drivers about the sharp curve.'),
(1,'wealth','a large amount of money or valuable things','The family built its wealth through trade.'),
(1,'whisper','to speak very quietly','She leaned over and whispered a secret.'),
(1,'willing','ready to do something if asked','He is willing to help us move.'),
(1,'wisdom','the ability to make good decisions based on experience','With age comes wisdom.'),
(1,'withdraw','to take money out of a bank or to take something back','He went to the bank to withdraw some cash.')
) as v(l, w, d, e)
where not exists (select 1 from public.words x where x.word = v.w);

insert into public.words(lvl, word, def, tr, ex)
select v.l, v.w, v.d, null, v.e from (values
(2,'acknowledge','to accept that something is true or exists','He had to acknowledge that he was wrong.'),
(2,'adapt','to change so that you can deal with a new situation','It took her a while to adapt to the new school.'),
(2,'agenda','a list of things to be discussed at a meeting','The first item on the agenda is the budget.'),
(2,'aggressive','ready to attack or behave in an angry way','The dog became aggressive when strangers came near.'),
(2,'allowance','an amount of money given regularly to someone','He spends his weekly allowance on comics.'),
(2,'applicant','a person who asks formally for a job or a place','There were fifty applicants for the position.'),
(2,'appropriate','right or suitable for a particular situation','Jeans are not appropriate for a wedding.'),
(2,'architect','a person who designs buildings','The architect showed us the plan of the house.'),
(2,'basis','the main idea or fact from which something develops','Trust is the basis of a good friendship.'),
(2,'commitment','a promise or strong decision to do something','Learning a language takes time and commitment.'),
(2,'conclude','to decide something after thinking about the facts','The doctors conclude that the medicine works.'),
(2,'conscious','awake and able to think','The patient was conscious after the operation.'),
(2,'consumer','a person who buys goods or services','Consumers want lower prices.'),
(2,'convince','to make someone believe that something is true','I could not convince him to come with us.'),
(2,'cooperate','to work together with other people','The students must cooperate to finish the project.'),
(2,'critic','a person who gives opinions about books, films or plays','The film critic loved the new movie.'),
(2,'crucial','extremely important for a result','Sleep is crucial for good health.'),
(2,'dedicate','to give a lot of your time and effort to something','She chose to dedicate her life to science.'),
(2,'demonstrate','to show clearly how something works','The teacher will demonstrate the experiment.'),
(2,'despair','a feeling of having lost all hope','He shouted in despair when he missed the bus.'),
(2,'detect','to notice or find something that is hard to see','Dogs can detect the smell of food from far away.'),
(2,'dilemma','a difficult choice between two things','She faced a dilemma between work and family.'),
(2,'distinguish','to see the difference between two things','It is hard to distinguish the twins.'),
(2,'eliminate','to remove something completely','We must eliminate waste in the factory.'),
(2,'emphasis','special importance given to something','The school puts emphasis on reading.'),
(2,'encounter','to meet someone or something unexpectedly','We may encounter some difficulties on the way.'),
(2,'excess','more than is needed or allowed','Excess weight can cause health problems.'),
(2,'frustrate','to make someone feel angry because they cannot do something','The slow internet can frustrate anyone.'),
(2,'hospitality','friendly and generous treatment of guests','We enjoyed the warm hospitality of our hosts.'),
(2,'illustrate','to add pictures to a book or to explain with examples','The book is illustrated with colourful drawings.'),
(2,'isolate','to keep someone or something separate from others','Doctors isolate sick patients to stop the disease.'),
(2,'occupy','to fill or use a place or time','Children occupy most of the playground.'),
(2,'quote','to repeat the words of another person exactly','He likes to quote famous poets.'),
(2,'recruit','to find new people to join a company or army','The company will recruit ten new workers.'),
(2,'represent','to speak or act officially for someone else','She will represent our school at the contest.'),
(2,'sacrifice','to give up something important for another person','Parents often sacrifice their free time for their children.'),
(2,'significant','important or large enough to be noticed','There is a significant difference between the two plans.'),
(2,'sincere','saying what you really feel','She gave a sincere apology.'),
(2,'slogan','a short phrase used in advertising or politics','The slogan of the shop is easy to remember.'),
(2,'spectacular','extremely impressive to look at','The view from the top was spectacular.'),
(2,'submit','to give a document or plan to someone for a decision','Students must submit their homework by Friday.'),
(2,'substance','any kind of solid, liquid or gas','The substance was a clear liquid.'),
(2,'sympathy','the feeling of being sorry for someone in trouble','She felt sympathy for the injured man.'),
(2,'triumph','a great victory or success','The win was a triumph for the young team.'),
(2,'venture','a new business or activity that involves some risk','The new venture made money in its first year.'),
(2,'verdict','the decision made by a jury in a court','The jury announced their verdict.'),
(2,'virtue','a good quality in a person','Patience is a great virtue.'),
(2,'voluntary','done because you choose to and not because you must','Attendance at the club is voluntary.'),
(2,'welfare','the health and happiness of people','The government cares about the welfare of its citizens.'),
(2,'workforce','all the people who work in a company or country','The factory has a large workforce.'),
(2,'accountable','responsible for your actions and ready to explain them','Managers are accountable for the mistakes of their teams.'),
(2,'adequate','enough or good enough for a particular purpose','The room was small but adequate for two people.'),
(2,'advocate','to publicly support an idea or a plan','Doctors advocate a healthy diet for children.'),
(2,'alliance','an agreement between countries or groups to work together','The two countries formed an alliance against the enemy.'),
(2,'ambiguous','having more than one possible meaning','His answer was ambiguous, so nobody understood it.'),
(2,'arguably','used when you think something can be supported by reasons','He is arguably the best player in the league.'),
(2,'assess','to judge how good, bad or important something is','Teachers assess students with a test every month.'),
(2,'assign','to give someone a job or task','The teacher will assign a project to each group.'),
(2,'attitude','the way you think or feel about something','She has a positive attitude to learning.'),
(2,'authority','the power to give orders or make decisions','Only the manager has the authority to sign this form.'),
(2,'bias','an unfair preference for one side','The newspaper showed a bias against the new law.'),
(2,'bold','brave and not afraid to take risks','It was a bold decision to leave her job.'),
(2,'brief','lasting only a short time','We had a brief meeting before lunch.'),
(2,'chaos','a state of complete confusion and disorder','The power cut caused chaos in the city.'),
(2,'circulate','to move around or pass from person to person','Blood circulates through the body.'),
(2,'cite','to mention something as an example or as proof','The writer cites several studies in her essay.'),
(2,'coincide','to happen at the same time as something else','My birthday coincides with the school holiday.'),
(2,'comparable','similar enough to be compared','The two cars are comparable in price.'),
(2,'compensate','to give someone something to make up for a loss','The airline will compensate passengers for the delay.'),
(2,'complement','to make something else look or taste better by adding to it','The red scarf complements her black coat.'),
(2,'compromise','an agreement in which each side gives up something','After a long talk, they reached a compromise.'),
(2,'conceal','to hide something so that it cannot be seen or known','He tried to conceal his disappointment.'),
(2,'concede','to admit that something is true after first denying it','She had to concede that her plan did not work.'),
(2,'confine','to keep something inside limits or in a small place','The disease was confined to a few villages.'),
(2,'constraint','something that limits what you can do','Lack of money is a major constraint for the project.'),
(2,'consult','to ask an expert or a book for advice','You should consult a doctor about your cough.'),
(2,'controversy','a public argument about something that people disagree on','The new school rule caused a lot of controversy.'),
(2,'convention','a way of behaving that most people accept as normal','It is a convention to shake hands when you meet someone.'),
(2,'cope','to deal successfully with a difficult situation','He finds it hard to cope with so much work.'),
(2,'credible','able to be believed or trusted','The witness gave a credible story.'),
(2,'criterion','a standard used to judge or decide something','Experience is the main criterion for this job.'),
(2,'deficit','the amount by which money spent is more than money received','The company has a deficit of two million dollars.'),
(2,'delegate','to give part of your work to someone else','A good leader knows how to delegate tasks.'),
(2,'demanding','needing a lot of effort or skill','Being a nurse is a demanding job.'),
(2,'deny','to say that something is not true','He will deny that he broke the window.'),
(2,'distinct','clearly different or easy to notice','The two languages have distinct sounds.'),
(2,'dominate','to have the most power or influence over something','One team has dominated the league this year.'),
(2,'doubt','a feeling of not being sure about something','I have no doubt that she will pass the exam.'),
(2,'dynamic','full of energy and new ideas','She is a dynamic leader who inspires everyone.'),
(2,'ensure','to make certain that something happens','Please ensure that all the lights are off.'),
(2,'entitle','to give someone the right to do or have something','This ticket entitles you to a free drink.'),
(2,'equip','to provide what is needed for a purpose','The school will equip every classroom with a computer.'),
(2,'essence','the most important quality of something','The essence of the story is the friendship between two boys.'),
(2,'ethic','a moral rule that guides behaviour','She has a strong work ethic and never misses a deadline.'),
(2,'exceed','to be more than a number or limit','Do not exceed the speed limit.'),
(2,'exploit','to use something fully, or to treat someone unfairly to benefit from them','Some companies exploit workers by paying them too little.'),
(2,'flaw','a mistake or weakness in something','The plan has a serious flaw.'),
(2,'gradual','happening slowly over a long time','There was a gradual improvement in her health.'),
(2,'grant','money given by an organisation for a particular purpose','The university gave her a grant to study abroad.'),
(2,'harsh','unpleasant, cruel or difficult to live with','The harsh winter killed many animals.'),
(2,'hinder','to make it difficult for something to happen','Heavy snow hindered the rescue work.'),
(2,'hypothesis','an idea that is suggested as an explanation but is not yet proved','The scientists tested their hypothesis in the lab.'),
(2,'identity','who a person is, or the qualities that make a person different','The police did not reveal the identity of the witness.'),
(2,'illusion','something that seems real but is not','The magician created the illusion of a floating ball.'),
(2,'immense','extremely large','The company made immense profits last year.'),
(2,'imply','to suggest something without saying it directly','Do not imply that I did something wrong.'),
(2,'inevitable','certain to happen and impossible to avoid','Change is inevitable in a growing city.'),
(2,'inspect','to look at something carefully to check it','The officer inspected every bag at the border.'),
(2,'integrate','to join different parts so they work as one','The school helps new students to integrate into the class.'),
(2,'intense','very strong or extreme','They felt intense heat in the desert.'),
(2,'interval','a period of time or a space between two events','There was a short interval between the two acts of the play.'),
(2,'intimate','very close and personal','They shared an intimate friendship for many years.'),
(2,'irony','a situation that is the opposite of what you expect','The irony is that the fire station burned down.'),
(2,'judgement','the ability to make good decisions','Use your judgement and do what you think is best.'),
(2,'keen','very interested or eager','She is keen on learning new languages.'),
(2,'likelihood','the chance that something will happen','There is a strong likelihood of rain this afternoon.'),
(2,'maintain','to keep something in good condition or at the same level','The workers maintain the roads in winter.'),
(2,'merely','only and nothing more','It was merely a mistake, not a lie.'),
(2,'migrate','to move from one place to another, especially birds or people','Many birds migrate south in the winter.'),
(2,'minimal','very small in amount','The damage to the car was minimal.'),
(2,'minority','a small part of a larger group','Only a minority of students voted for the change.'),
(2,'motive','the reason why someone does something','The police could not find a motive for the crime.'),
(2,'negotiate','to discuss something to reach an agreement','The workers negotiated for a better salary.'),
(2,'notorious','famous for something bad','The road is notorious for accidents.'),
(2,'objective','something you plan to achieve','Our main objective is to finish the project by May.'),
(2,'obligation','something you must do because of a law or a promise','Parents have an obligation to look after their children.'),
(2,'occasional','happening sometimes but not often','We have an occasional walk in the park on Sundays.'),
(2,'odds','the chance that something will or will not happen','The odds of winning the lottery are very small.'),
(2,'opponent','a person you play or fight against','He shook hands with his opponent after the match.'),
(2,'outline','a short description of the main points of something','The teacher asked us to write an outline of the essay.'),
(2,'overall','taking everything into account','Overall, the trip was a great success.'),
(2,'overlook','to fail to notice something','He overlooked a small mistake in the report.'),
(2,'oversee','to watch and direct the work of other people','She oversees a team of twenty workers.'),
(2,'parallel','going in the same direction and always the same distance apart','The road runs parallel to the river.'),
(2,'perceive','to notice or understand something in a particular way','Many people perceive him as a kind man.'),
(2,'persist','to continue to do something in a determined way','If the pain persists, see a doctor.'),
(2,'phenomenon','an event or fact that can be seen and is often unusual','The northern lights are a natural phenomenon.'),
(2,'plausible','likely to be true','His excuse sounded plausible at first.'),
(2,'potential','the ability to develop in the future','The young player has great potential.'),
(2,'precise','exact and accurate','Can you give me a precise time?'),
(2,'priority','something that is more important than other things','Safety is our first priority.'),
(2,'prohibit','to officially stop something by law','The law prohibits smoking in public places.'),
(2,'prompt','done quickly and without delay','Thank you for your prompt reply.'),
(2,'proportion','a part or share of a whole','A large proportion of the students walk to school.'),
(2,'prospect','the chance that something will happen in the future','The prospect of going to the beach made her smile.'),
(2,'provoke','to cause a strong reaction, often an angry one','The joke provoked an angry reply.'),
(2,'ratio','the relationship between two amounts','The ratio of boys to girls in the class is two to one.'),
(2,'rational','based on clear thought rather than feelings','There must be a rational explanation for the noise.'),
(2,'reluctance','unwillingness to do something','She showed no reluctance to help.'),
(2,'resemble','to look like or be similar to someone or something','The boy resembles his father.'),
(2,'restore','to bring something back to its original condition','They worked hard to restore the old church.'),
(2,'restrain','to stop someone or something from doing something','The guard had to restrain the angry dog.'),
(2,'resume','to start again after a pause','The match will resume after the rain stops.'),
(2,'retain','to keep something rather than lose it','The old house has retained its original windows.'),
(2,'revise','to change something to make it better, or to study again for an exam','I need to revise my notes before the test.'),
(2,'rigid','stiff and not easy to bend or change','The company has rigid rules about clothes.'),
(2,'rural','connected with the countryside','She grew up in a rural area.'),
(2,'scope','the range of things that something deals with','The scope of the project is very wide.'),
(2,'sector','one part of the economy or society','The tourism sector employs many people here.'),
(2,'seek','to try to find or get something','They seek help from the local government.'),
(2,'sequence','a set of events or actions that follow each other in a fixed order','Put these pictures in the right sequence.'),
(2,'shift','to move or change from one position to another','The wind shifted and came from the north.'),
(2,'simulate','to copy the conditions of something for training or testing','Pilots use machines that simulate real flights.'),
(2,'spark','a very small bit of fire or a small beginning of something','A spark from the fire burned a hole in the carpet.'),
(2,'specify','to say something clearly and exactly','The form asks you to specify your date of birth.'),
(2,'statistic','a number that shows facts about something','That statistic surprised everyone in the room.'),
(2,'strategy','a plan for achieving something over time','The team changed its strategy in the second half.'),
(2,'subtle','not obvious and difficult to notice','There was a subtle difference in the colour.'),
(2,'sufficient','as much as is needed','We have sufficient food for the trip.'),
(2,'summarise','to give the main points of something briefly','Can you summarise the story in two sentences?'),
(2,'supplement','something added to improve or complete something','She takes a vitamin supplement every morning.'),
(2,'surplus','an amount that is more than is needed','The farmers had a surplus of apples this year.'),
(2,'survey','a set of questions asked to find out what people think','The school did a survey about lunch.'),
(2,'sustainable','able to continue without harming the environment','The town wants to build more sustainable homes.'),
(2,'tendency','something that a person or thing often does','He has a tendency to arrive late.'),
(2,'thesis','a long piece of writing for a university degree','She spent two years writing her thesis.'),
(2,'tone','the way something sounds or the feeling in someone''s voice','His angry tone made everyone quiet.'),
(2,'trigger','to cause something to start','Loud noises can trigger a headache.'),
(2,'undergo','to experience something unpleasant or important','He had to undergo a long operation.'),
(2,'urban','connected with towns and cities','Urban areas are growing quickly.'),
(2,'utility','a basic service such as water, gas or electricity','Utility costs are higher in winter.'),
(2,'vague','not clear or exact','He gave only a vague answer.'),
(2,'valid','acceptable according to rules, or based on good reasons','Your passport must be valid for six months.'),
(2,'vary','to be different or change from one situation to another','Prices vary from shop to shop.'),
(2,'vast','extremely large in area or amount','The vast desert stretched in every direction.'),
(2,'verify','to check that something is true','Please verify your email address.'),
(2,'visible','able to be seen','The mountains were visible from far away.')
) as v(l, w, d, e)
where not exists (select 1 from public.words x where x.word = v.w);

insert into public.words(lvl, word, def, tr, ex)
select v.l, v.w, v.d, null, v.e from (values
(3,'abolish','to officially end a law, system or custom','Many countries abolished slavery in the nineteenth century.'),
(3,'abrupt','sudden and often unpleasant','The meeting came to an abrupt end.'),
(3,'absurd','completely unreasonable or silly','It is absurd to pay so much for an old chair.'),
(3,'accelerate','to go faster or make something happen faster','The car began to accelerate on the empty road.'),
(3,'accessible','easy to reach, enter or understand','The museum is accessible by bus and train.'),
(3,'accommodate','to provide space or a place for someone','The hotel can accommodate two hundred guests.'),
(3,'adjacent','next to or very near something','The school is adjacent to the park.'),
(3,'affiliate','to connect a smaller group or organisation to a larger one','The club is affiliated with the national league.'),
(3,'albeit','although','He finished the race, albeit very slowly.'),
(3,'allege','to say that someone has done something wrong without proof','The newspaper alleges that the mayor took money.'),
(3,'ambiguity','the state of having more than one possible meaning','The ambiguity in the contract caused many problems.'),
(3,'amend','to change a text or law to improve it','The government decided to amend the old law.'),
(3,'analogy','a comparison that shows how two things are alike','The teacher used an analogy to explain the heart.'),
(3,'ancestry','your family''s origins through earlier generations','She is proud of her Greek ancestry.'),
(3,'apparatus','the tools and equipment used for a particular activity','The scientists set up the apparatus in the lab.'),
(3,'arbitrary','decided by chance or personal choice rather than reason','The choice of colours seemed arbitrary.'),
(3,'ascertain','to find out something and be sure of it','The police tried to ascertain the cause of the fire.'),
(3,'aspect','one part or feature of a situation','Safety is an important aspect of the job.'),
(3,'autonomy','the freedom to make your own decisions','The new manager gave the team more autonomy.'),
(3,'backlash','a strong negative reaction from many people','The new tax caused a backlash among workers.'),
(3,'bizarre','very strange and unusual','He told us a bizarre story about a talking cat.'),
(3,'bolster','to make something stronger or more confident','The win will bolster the team''s hopes.'),
(3,'brink','the edge of a dangerous or exciting event','The company was on the brink of closing.'),
(3,'bureaucracy','a complicated system of rules in government or business','Getting a permit involves a lot of bureaucracy.'),
(3,'catastrophe','a sudden event that causes great damage or suffering','The earthquake was a terrible catastrophe.'),
(3,'characteristic','a typical quality of a person or thing','Kindness is her best characteristic.'),
(3,'chronic','lasting for a long time or happening again and again','He suffers from chronic back pain.'),
(3,'cognitive','connected with the process of thinking and understanding','Reading helps children''s cognitive development.'),
(3,'collaborate','to work together with others on a shared task','Two schools will collaborate on the science project.'),
(3,'commodity','a product that can be bought and sold','Oil is a valuable commodity.'),
(3,'condemn','to say publicly that something is very bad','Leaders around the world condemn the attack.'),
(3,'consecutive','following one after another without a break','It rained for five consecutive days.'),
(3,'consent','permission or agreement to do something','You need your parents'' consent to join the trip.'),
(3,'consumption','the amount of something that is used or eaten','The city wants to reduce its energy consumption.'),
(3,'contaminate','to make something dirty or poisonous','Chemicals from the factory contaminated the river.'),
(3,'conventional','following what is traditional or usual','He prefers conventional medicine to herbal treatments.'),
(3,'convert','to change something into a different form or use','They plan to convert the old barn into a house.'),
(3,'correlate','to have a connection where one thing affects another','Studies show that good sleep correlates with better grades.'),
(3,'curb','to control or limit something','The city introduced new rules to curb pollution.'),
(3,'deficiency','a lack of something that is necessary','A vitamin deficiency can make you feel tired.'),
(3,'degrade','to make something worse in quality','Pollution can degrade the soil.'),
(3,'deploy','to put people or equipment into position for use','The army deployed more soldiers to the border.'),
(3,'deprive','to take something important away from someone','The prisoners were deprived of sunlight.'),
(3,'designate','to choose someone or something for a particular purpose','The council designated the area a nature reserve.'),
(3,'detach','to remove something from the thing it is joined to','You can detach the hood from the jacket.'),
(3,'detrimental','causing harm or damage','Too much sugar is detrimental to your health.'),
(3,'deviate','to move away from the usual or expected way','Please do not deviate from the plan.'),
(3,'discern','to see or understand something that is not obvious','I could not discern the shape in the fog.'),
(3,'discrete','separate and clearly different','The course is divided into three discrete parts.'),
(3,'disparity','a big difference between things that should be equal','There is a large disparity between rich and poor areas.'),
(3,'displace','to force people or things to leave their usual place','The floods displaced thousands of families.'),
(3,'disposal','the act of getting rid of something','The disposal of waste is a major problem.'),
(3,'dissolve','to mix into a liquid and become part of it','Sugar dissolves quickly in hot water.'),
(3,'doctrine','a set of beliefs taught by a group or church','The group follows a strict religious doctrine.'),
(3,'dubious','not completely honest or doubtful','He made a dubious offer to sell the car cheaply.'),
(3,'eligible','having the right to do or receive something','You are eligible to vote when you are eighteen.'),
(3,'embark','to start a journey or a new project','They embarked on a long journey across Asia.'),
(3,'embrace','to accept an idea or change with enthusiasm','The school embraced the new technology.'),
(3,'empower','to give someone more control over their life','Education empowers young women.'),
(3,'encompass','to include a large range of things','The course encompasses history, art and music.'),
(3,'endorse','to say publicly that you support something','The famous singer endorsed the new trainers.'),
(3,'enrol','to officially join a course or school','She decided to enrol in a cooking class.'),
(3,'entail','to involve something as a necessary part','The job entails a lot of travelling.'),
(3,'entity','something that exists separately from other things','The school is a separate legal entity.'),
(3,'envisage','to imagine something as possible in the future','They envisage a world without hunger.'),
(3,'equilibrium','a state in which opposing forces are balanced','The scales reached a state of equilibrium.'),
(3,'erratic','not regular or predictable','The train service has been erratic this week.'),
(3,'ethical','connected with moral principles of right and wrong','Is it ethical to test medicine on animals?'),
(3,'evoke','to bring a feeling or memory into your mind','The smell of bread evokes memories of my childhood.'),
(3,'exempt','free from a rule or duty that applies to others','Students are exempt from paying the fee.'),
(3,'exert','to use strength or influence to do something','He exerted all his strength to open the door.'),
(3,'explicit','stated clearly and in detail','The teacher gave explicit instructions for the test.'),
(3,'extract','to take something out, often with effort','The dentist had to extract a tooth.'),
(3,'fabricate','to invent false information in order to deceive','He fabricated an excuse for missing the class.'),
(3,'feasible','possible to do or achieve','It is not feasible to finish the work in one day.'),
(3,'forthcoming','about to happen soon','Details of the forthcoming event will be sent by email.'),
(3,'fraction','a small part or amount of something','He finished the exam in a fraction of the time.'),
(3,'framework','a basic structure that supports or guides something','The law sets a framework for new schools.'),
(3,'gauge','to judge or measure something such as an opinion','It is difficult to gauge how people will react.'),
(3,'grasp','to understand something completely, or to hold something tightly','She quickly grasped the idea.'),
(3,'hamper','to make it difficult for someone to move or act','Heavy traffic hampered the ambulance.'),
(3,'illuminate','to light up a place or make something clear','Candles illuminated the dark room.'),
(3,'impair','to damage something so that it does not work well','Loud noise can impair your hearing.'),
(3,'implication','a possible result or effect of something','The report discusses the implication of the new law.'),
(3,'implicit','suggested without being said directly','There was an implicit threat in his words.'),
(3,'inadequate','not enough or not good enough','The building has inadequate fire exits.'),
(3,'inception','the start of an organisation or activity','Since its inception, the club has grown quickly.'),
(3,'incidence','the rate at which something happens','The incidence of the disease has fallen this year.'),
(3,'indicate','to show or point to something','The sign indicates the way to the station.'),
(3,'induce','to cause something to happen','The medicine may induce sleep.'),
(3,'initiate','to start something such as a plan or process','The mayor initiated a project to clean the river.'),
(3,'innovate','to introduce new ideas or methods','Companies must innovate to stay ahead.'),
(3,'instigate','to cause something to start, often something bad','He tried to instigate a fight between the two teams.'),
(3,'institute','to start or introduce a rule or system','The school instituted a new reading programme.'),
(3,'integrity','the quality of being honest and having strong principles','The judge is known for her integrity.'),
(3,'intensify','to become stronger or increase in degree','The storm will intensify overnight.'),
(3,'intermediate','in the middle between two levels','She is at an intermediate level in English.'),
(3,'intrinsic','belonging to the basic nature of something','Honesty has an intrinsic value.'),
(3,'invoke','to mention a law or idea to support your case','The lawyer invoked an old law to defend his client.'),
(3,'irrelevant','not connected with the subject being discussed','His comment was irrelevant to the discussion.'),
(3,'jurisdiction','the official power to make legal decisions in an area','The case is outside the court''s jurisdiction.'),
(3,'liable','legally responsible for something','The owner is liable for any damage.'),
(3,'likewise','in the same way','She smiled and he did likewise.'),
(3,'mainstream','ideas or tastes that are accepted by most people','He prefers mainstream music to jazz.'),
(3,'manifest','to show something clearly','The disease may manifest itself in different ways.'),
(3,'margin','the empty space at the edge of a page, or a small difference','She wrote notes in the margin of the book.'),
(3,'mechanism','a part of a machine or a system that does a particular job','The mechanism of the clock is very complicated.'),
(3,'merge','to combine two things so that they become one','The two banks plan to merge next year.'),
(3,'methodology','a system of methods used in a particular area of study','The scientists explained their methodology in the report.'),
(3,'milestone','an important event in the development of something','Learning to walk is a big milestone for a baby.'),
(3,'mobilise','to organise people or resources to take action','The charity mobilised hundreds of volunteers.'),
(3,'moreover','in addition to what has been said','The room is small. Moreover, it is very dark.'),
(3,'negate','to make something have no effect','One mistake can negate all your hard work.'),
(3,'negligible','so small that it is not important','The risk to your health is negligible.'),
(3,'nonetheless','in spite of what has just been said','It was raining, but we went out nonetheless.'),
(3,'norm','a standard or usual way of behaving','Working from home has become the norm for many people.'),
(3,'nurture','to care for and help something grow','Good teachers nurture young talent.'),
(3,'obsolete','no longer used because something better exists','Typewriters are now obsolete.'),
(3,'omit','to leave something out','Please do not omit any details from your report.'),
(3,'ongoing','continuing to happen now','The ongoing repairs have closed the road.'),
(3,'outweigh','to be more important than something else','The advantages of the plan outweigh the costs.'),
(3,'paradigm','a typical example or pattern of something','The invention changed the paradigm of modern travel.'),
(3,'parameter','a limit or rule that affects how something is done','The parameters of the test are explained on the first page.'),
(3,'partial','not complete','He gave only a partial explanation.'),
(3,'plight','a difficult or sad situation','The charity highlights the plight of homeless people.'),
(3,'portray','to show someone or something in a particular way','The film portrays her as a brave leader.'),
(3,'potent','very strong or powerful','The medicine is very potent.'),
(3,'precedent','an earlier action that is used as an example','The decision sets a precedent for future cases.'),
(3,'predecessor','a person who held a job before another person','My predecessor left clear instructions in the office.'),
(3,'preliminary','coming before the main part of something','The preliminary results were published last week.'),
(3,'premise','an idea that you accept as true and use as a base for argument','The argument was based on a false premise.'),
(3,'prevail','to be common or widespread, or to win','Common sense will prevail in the end.'),
(3,'primary','most important or first in order','Safety is our primary concern.'),
(3,'prior','existing or coming before something else','You need prior permission to enter this area.'),
(3,'privilege','a special right or advantage given to a person or group','Having a good education is a privilege.'),
(3,'proceed','to continue to do something','Please proceed to gate number five.'),
(3,'projection','an estimate of something in the future based on facts','The sales projection for next year looks very good.'),
(3,'provision','the act of providing something that is needed','The government is responsible for the provision of schools.'),
(3,'pursuit','the act of chasing or trying to get something','The dog ran off in pursuit of a rabbit.'),
(3,'rebel','to fight against authority or refuse to obey','Teenagers sometimes rebel against their parents.'),
(3,'reconcile','to make two people friends again after an argument','They finally reconciled after years of silence.'),
(3,'regime','a government, especially one that is not elected fairly','The old regime ended after the revolution.'),
(3,'reimburse','to pay back money that someone has spent','The company will reimburse your travel costs.'),
(3,'relevance','the importance of something to a particular subject','I do not see the relevance of this question.'),
(3,'render','to cause someone or something to be in a particular state','The accident rendered him unable to work.'),
(3,'replicate','to copy something exactly','Scientists tried to replicate the results of the experiment.'),
(3,'reside','to live in a particular place','He resides in a small village near the coast.'),
(3,'retrieve','to get something back from a place','The dog went to retrieve the stick.'),
(3,'revenue','the money that a company or government receives','The theatre earns revenue from ticket sales.'),
(3,'revolve','to move around a central point','The earth revolves around the sun.'),
(3,'ritual','a set of actions always done in the same way','They have a ritual of drinking tea every morning.'),
(3,'sceptical','having doubts about whether something is true','I am sceptical about his promise.'),
(3,'segment','one of the parts that something is divided into','Each segment of the orange was sweet and juicy.'),
(3,'seize','to take something quickly and firmly','The police seized the stolen goods.'),
(3,'simultaneous','happening at exactly the same time','The two explosions were almost simultaneous.'),
(3,'sovereign','having the highest power in a country','The country became a sovereign state in 1991.'),
(3,'speculate','to guess about something without enough information','People speculate about who will win the election.'),
(3,'stereotype','a fixed and often unfair idea about a group of people','The film uses a stereotype about old people.'),
(3,'stimulus','something that causes a reaction or encourages growth','Exercise is a stimulus for the brain.'),
(3,'strive','to try very hard to achieve something','She strives to be the best in her class.'),
(3,'subordinate','less important or lower in rank','A subordinate must follow the orders of the manager.'),
(3,'subsidy','money given by the government to help an industry','Farmers receive a subsidy for growing wheat.'),
(3,'successor','a person who takes over a job from someone else','The president chose his successor carefully.'),
(3,'suspend','to stop something for a period of time','The school suspended classes because of the snow.'),
(3,'tangle','a twisted mass of things such as hair or string','The cat made a tangle of the wool.'),
(3,'terminate','to end something officially','The company terminated his contract.'),
(3,'thereby','as a result of that action','He saved money, thereby increasing his profit.'),
(3,'thrive','to grow or develop well','Plants thrive in warm and wet conditions.'),
(3,'trait','a particular quality in someone''s character','Honesty is her best trait.'),
(3,'transmit','to send or pass something from one place to another','Mosquitoes can transmit serious diseases.'),
(3,'trivial','not important or serious','They argued about a trivial matter.'),
(3,'turmoil','a state of great confusion or trouble','The country was in turmoil after the election.'),
(3,'unify','to bring things together to form a single unit','The new leader tried to unify the country.'),
(3,'unveil','to show or announce something for the first time','The company will unveil its new phone next week.'),
(3,'utilise','to make use of something','We can utilise the old building as a library.'),
(3,'validate','to prove that something is true or acceptable','The results validate the scientist''s theory.'),
(3,'vigorous','strong, energetic and full of life','He took a vigorous walk every morning.'),
(3,'violate','to break a rule, law or agreement','The company violated safety rules.'),
(3,'virtual','existing on a computer rather than in the real world','We took a virtual tour of the museum.'),
(3,'whereas','used to show a difference between two things','My sister likes pop music, whereas I like jazz.'),
(3,'whilst','at the same time as','He read a book whilst waiting for the bus.'),
(3,'withhold','to refuse to give something','The bank may withhold money from his account.'),
(3,'withstand','to remain unharmed by something','The old bridge can withstand strong winds.'),
(3,'worthwhile','useful or enjoyable enough to deserve your time or effort','The long trip was worthwhile.')
) as v(l, w, d, e)
where not exists (select 1 from public.words x where x.word = v.w);
